@baseUrl = http://localhost:8090/api

# ================= BOOK TESTS =================

### 1. Create a new Book
# @name createBookRequest
POST {{baseUrl}}/books
Content-Type: application/json

{
  "title": "The Pragmatic Programmer",
  "author": "Andrew Hunt",
  "publicationYear": 1999,
  "file": {
    "type": "pdf",
    "url": "http://example.com/pragmatic.pdf"
  }
}

### 2. Get All Books
GET {{baseUrl}}/books

#
### 3. Get Specific Book by ID
GET {{baseUrl}}/books/694166b3ee8e625b359cf3ac


# ================= COMS TESTS =================

### 4. Create a new Com
POST {{baseUrl}}/coms
Content-Type: application/json

{
  "bookid": "694166b3ee8e625b359cf3ac",
  "text": "Madhav pay me",
  "user": "actual_dev33"
}

### 5. Get All Coms
GET {{baseUrl}}/coms

### 3. Fetch comments by bookid
GET {{baseUrl}}/coms/book/694397158b5ab55bed70892b
Accept: application/json

### Get user's favorite books
GET {{baseUrl}}/users/69441637d3aa1450c897e434/favbooks
Accept: application/json


### Add book to favorites
POST {{baseUrl}}/users/69441637d3aa1450c897e434/favbooks/6941648aee8e625b359cf3a5
Accept: application/json


### add a user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "firebaseUid": "test123firebase",
  "username": "testuser",
  "email": "test@example.com",
  "favBooks": []
}
