@baseUrl = http://localhost:8090/api

# ================= BOOK TESTS =================

### 1. Create a new Book
# @name createBookRequest
POST {{baseUrl}}/books
Content-Type: application/json

{
  "title": "The Pragmatic Programmer",
  "author": "Andrew Hunt",
  "publicationYear": 1999,
  "file": {
    "type": "pdf",
    "url": "http://example.com/pragmatic.pdf"
  }
}

### 2. Get All Books
GET {{baseUrl}}/books

#
## 3. Get Specific Book by ID
# This uses the ID from the response of request 
GET {{baseUrl}}/books/6941648aee8e625b359cf3a5


# ================= COMS TESTS =================

### 4. Create a new Com
POST {{baseUrl}}/coms
Content-Type: application/json

{
  "bookid": "694388778b5ab55bed708926",
  "text": "This API is working perfectly.",
  "user": "DevUser"
}

### 5. Get All Coms
GET {{baseUrl}}/coms